import { Type } from 'class-transformer';
import { IsBoolean, IsInt, IsNotEmpty, IsNumber, IsOptional, IsString, MaxLength, Min } from 'class-validator';

export class CreateProdutoDto {

    @IsString()
    @IsNotEmpty()
    @MaxLength(150)
    nome: string;

    @IsString()
    @IsOptional()
    @MaxLength(50)
    codigo?: string;

    @IsString()
    @IsOptional()
    @MaxLength(500)
    descricao?: string;

    // id is generated by DB on insert; keep optional if present
    @Type(() => Number)
    @IsInt()
    @IsOptional()
    id?: number;

    @Type(() => Number)
    @IsInt()
    @IsNotEmpty()
    id_unidade_medida: number;

    @Type(() => Number)
    @IsInt()
    @IsOptional()
    id_marca?: number;

    @Type(() => Number)
    @IsInt()
    @IsOptional()
    id_categoria?: number;

    @Type(() => Number)
    @IsInt()
    @IsNotEmpty()
    responsavel_cadastro: number;

    @Type(() => Number)
    @IsInt()
    @IsOptional()
    usuario_log_id?: number;

    @Type(() => Number)
    @IsNumber()
    @IsOptional()
    @Min(0)
    estoque_minimo?: number;

    @IsBoolean()
    @IsOptional()
    ativo?: boolean;

    @IsBoolean()
    @IsOptional()
    is_perecivel?: boolean;

    // estoque_minimo e outros numéricos podem ser tratados no service; mantemos somente typing here
}
