/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Categorias: typeof import('./components/categorias/Categorias.vue')['default']
    Depositos: typeof import('./components/locais/Depositos.vue')['default']
    DonutChartCard: typeof import('./components/dashboards/DonutChartCard.vue')['default']
    FiltrosRelatorios: typeof import('./components/shared/FiltrosRelatorios.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Fornecedores: typeof import('./components/fornecedores/Fornecedores.vue')['default']
    GraficoBarrasCompleto: typeof import('./components/dashboards/GraficoBarrasCompleto.vue')['default']
    Localizacoes: typeof import('./components/locais/Localizacoes.vue')['default']
    LocationHierarchy: typeof import('./components/locais/LocationHierarchy.vue')['default']
    Marcas: typeof import('./components/produtos/Marcas.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    ReportsStatsCards: typeof import('./components/dashboards/ReportsStatsCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/shared/StatCard.vue')['default']
    UnidadesMedida: typeof import('./components/produtos/UnidadesMedida.vue')['default']
    UserCard: typeof import('./components/usuarios/UserCard.vue')['default']
    UserForm: typeof import('./components/usuarios/UserForm.vue')['default']
    UsersTable: typeof import('./components/usuarios/UsersTable.vue')['default']
    UserStatsCards: typeof import('./components/usuarios/UserStatsCards.vue')['default']
    UserViewDialog: typeof import('./components/usuarios/UserViewDialog.vue')['default']
  }
}
