/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Categorias: typeof import('./src/components/categorias/Categorias.vue')['default']
    CreateMovementDialog: typeof import('./src/components/estoques/CreateMovementDialog.vue')['default']
    Depositos: typeof import('./src/components/locais/Depositos.vue')['default']
    DonutChartCard: typeof import('./src/components/dashboards/DonutChartCard.vue')['default']
    FiltrosRelatorios: typeof import('./src/components/shared/FiltrosRelatorios.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Fornecedores: typeof import('./src/components/fornecedores/Fornecedores.vue')['default']
    GraficoBarrasCompleto: typeof import('./src/components/dashboards/GraficoBarrasCompleto.vue')['default']
    Localizacoes: typeof import('./src/components/locais/Localizacoes.vue')['default']
    LocationHierarchy: typeof import('./src/components/locais/LocationHierarchy.vue')['default']
    Marcas: typeof import('./src/components/produtos/Marcas.vue')['default']
    MovimentacaoHeader: typeof import('./src/components/estoques/MovimentacaoHeader.vue')['default']
    MovimentacaoStats: typeof import('./src/components/estoques/MovimentacaoStats.vue')['default']
    MovimentacaoTable: typeof import('./src/components/estoques/MovimentacaoTable.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    ReportsStatsCards: typeof import('./src/components/dashboards/ReportsStatsCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/shared/StatCard.vue')['default']
    UnauthorizedDialog: typeof import('./src/components/shared/UnauthorizedDialog.vue')['default']
    UnidadesMedida: typeof import('./src/components/produtos/UnidadesMedida.vue')['default']
    UserCard: typeof import('./src/components/usuarios/UserCard.vue')['default']
    UserForm: typeof import('./src/components/usuarios/UserForm.vue')['default']
    UsersTable: typeof import('./src/components/usuarios/UsersTable.vue')['default']
    UserStatsCards: typeof import('./src/components/usuarios/UserStatsCards.vue')['default']
    UserViewDialog: typeof import('./src/components/usuarios/UserViewDialog.vue')['default']
    ViewMovementDialog: typeof import('./src/components/estoques/ViewMovementDialog.vue')['default']
  }
}
